version: '3.7'

services:
  web:
    build: 
      context: ./services/web
      dockerfile: Dockerfile
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/NODE_ENV=developmentdata/
    environment:
      - POSTGRES_USER=flask
      - POSTGRES_PASSWORD=flask

  nginx:
    build: 
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - web
      - client

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - './services/client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3007:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    stdin_open: true
    depends_on:
      - web

volumes:
  postgres_data:
